apiVersion: scheduling.upbound.io/v1alpha1
kind: Environment
metadata:
  name: default
  namespace: default
spec:
  dimensions:
    offering: db
  resourceGroups:
    - name: db.idp.upbound.io
      dimensions:
        offering: db
