apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: subnets.networking.idp.upbound.io
spec:
  group: networking.idp.upbound.io
  names:
    categories:
    - crossplane
    kind: Subnet
    plural: subnets
  claimNames:
    kind: SubnetClaim
    plural: subnetclaims
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: Subnet is the Schema for the Subnet API.
        properties:
          spec:
            description: SubnetSpec defines the desired state of Subnet.
            properties:
              parameters:
                properties:
                  availabilityZone:
                    type: string
                  cidrBlock:
                    type: string
                  region:
                    type: string
                  type:
                    type: string
                type: object
            type: object
          status:
            description: SubnetStatus defines the observed state of Subnet.
            type: object
        required:
        - spec
        type: object
    served: true
