apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: functions.compute.idp.upbound.io
spec:
  group: compute.idp.upbound.io
  names:
    categories:
    - crossplane
    kind: Function
    plural: functions
  claimNames:
    kind: FunctionClaim
    plural: functionclaims
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: Function is the Schema for the Function API.
        properties:
          spec:
            description: FunctionSpec defines the desired state of Function.
            properties:
              parameters:
                properties:
                  deployment:
                    properties:
                      bucketName:
                        type: string
                      bucketObjectKey:
                        type: string
                      bucketObjectVersion:
                        type: string
                      handler:
                        type: string
                    type: object
                  region:
                    type: string
                type: object
            type: object
          status:
            description: FunctionStatus defines the observed state of Function.
            type: object
        required:
        - spec
        type: object
    served: true
