apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: subnets.networking.idp.upbound.io
spec:
  compositeTypeRef:
    apiVersion: networking.idp.upbound.io/v1alpha1
    kind: Subnet
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-idp-networkingcompose-subnet
    step: compose-subnet
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
