apiVersion: db.idp.upbound.io/v1alpha1
kind: SQLInstanceClaim
metadata:
  name: example
  namespace: default
spec:
  parameters:
    engine: postgres
    engineVersion: '12'
    instanceClass: db.t3
    networkRef:
      apiVersion: networking.idp.upbound.io/v1alpha1
      grants:
        - Observe
      kind: NetworkClaim
      name: example # This references the NetworkClaim/example in the other project in this monorepo
    password:
      autoGeneratePassword: false
      passwordSecretKey: password
      passwordSecretRef:
        apiVersion: v1
        grants:
          - "*"
        kind: Secret
        name: db-secret
        namespace: default
    region: EU West
    storageGB: 10
