apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: accounts.iam.idp.upbound.io
spec:
  compositeTypeRef:
    apiVersion: iam.idp.upbound.io/v1alpha1
    kind: Account
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-idp-iamcompose-account
    step: compose-account
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
