apiVersion: ai.idp.upbound.io/v1alpha1
kind: ModelClaim
metadata:
  name: example
spec:
  parameters:
    model:
      name: "falcon-7b"
      path: "https://raw.githubusercontent.com/Azure/kaito/main/examples/inference/kaito_workspace_falcon_7b-instruct.yaml"
    clusterRef:
      apiVersion: compute.idp.upbound.io/v1alpha1
      grants:
      - "*"
      kind: ClusterClaim
      name: example
      namespace: default
