apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: networks.networking.idp.upbound.io
  annotations:
    references.upbound.io/schema: '{"apiVersion":"references.upbound.io/v1alpha1","kind":"ReferenceSchema","references":[{"jsonPath":".spec.parameters.subnets.items.subnetRef","kinds":[{"apiVersion":"networking.idp.upbound.io","kind":"SubnetClaim"}]}]}'
spec:
  group: networking.idp.upbound.io
  names:
    categories:
    - crossplane
    kind: Network
    plural: networks
  claimNames:
    kind: NetworkClaim
    plural: networkclaims
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: Network is the Schema for the Network API.
        properties:
          spec:
            description: NetworkSpec defines the desired state of Network.
            properties:
              parameters:
                properties:
                  region:
                    type: string
                  subnets:
                    items:
                      properties:
                        parameters:
                          properties:
                            availabilityZone:
                              type: string
                            cidrBlock:
                              type: string
                            type:
                              type: string
                          type: object
                        subnetRef:
                          properties:
                            apiVersion:
                              type: string
                            grants:
                              items:
                                type: string
                              type: array
                            kind:
                              type: string
                            name:
                              type: string
                          type: object
                      type: object
                    type: array
                  vpcCidrBlock:
                    type: string
                type: object
            type: object
          status:
            description: NetworkStatus defines the observed state of Network.
            type: object
        required:
        - spec
        type: object
    served: true
