apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: serviceaccounts.iam.idp.upbound.io
spec:
  compositeTypeRef:
    apiVersion: iam.idp.upbound.io/v1alpha1
    kind: ServiceAccount
  mode: Pipeline
  pipeline:
  - functionRef:
      name: acmeco-iamcompose-sa
    step: compose-sa
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
