apiVersion: bootstrap.idp.upbound.io/v1alpha1
kind: ServiceProvider
metadata:
  name: networking
  namespace: default
spec: {}
---
apiVersion: bootstrap.idp.upbound.io/v1alpha1
kind: ServiceControlPlane
metadata:
  name: production
  namespace: default
spec:
  parameters:
    serviceProviderRef:
      name: networking
      namespace: networking