apiVersion: v1
kind: Namespace
metadata:
  name: storage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec: {}
---
apiVersion: bootstrap.idp.upbound.io/v1alpha1
kind: ServiceProvider
metadata:
  name: storage
  namespace: storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec: {}
---
apiVersion: bootstrap.idp.upbound.io/v1alpha1
kind: ServiceControlPlane
metadata:
  name: production
  namespace: storage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  parameters:
    serviceProviderRef:
      name: storage
      namespace: storage