apiVersion: bootstrap.idp.upbound.io/v1alpha1
kind: ServiceProvider
metadata:
  name: storage
  namespace: default
spec: {}
---
apiVersion: bootstrap.idp.upbound.io/v1alpha1
kind: ServiceControlPlane
metadata:
  name: production
  namespace: default
spec:
  parameters:
    serviceProviderRef:
      name: storage
      namespace: storage