apiVersion: v1
kind: Namespace
metadata:
  name: networking
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec: {}
---
apiVersion: bootstrap.idp.upbound.io/v1alpha1
kind: ServiceProvider
metadata:
  name: networking
  namespace: networking
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec: {}
---
apiVersion: bootstrap.idp.upbound.io/v1alpha1
kind: ServiceControlPlane
metadata:
  name: production
  namespace: networking
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  parameters:
    serviceProviderRef:
      name: networking
      namespace: networking