apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xserviceproviders.bootstrap.idp.upbound.io
spec:
  compositeTypeRef:
    apiVersion: bootstrap.idp.upbound.io/v1alpha1
    kind: XServiceProvider
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-fabriccompose-serviceprovider
    step: compose-serviceprovider
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
