apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: buckets.storage.idp.upbound.io
spec:
  group: storage.idp.upbound.io
  names:
    categories:
    - crossplane
    kind: Bucket
    plural: buckets
  claimNames:
    kind: BucketClaim
    plural: bucketclaims
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: Bucket is the Schema for the Bucket API.
        properties:
          spec:
            description: BucketSpec defines the desired state of Bucket.
            properties:
              parameters:
                properties:
                  region:
                    type: string
                type: object
            type: object
          status:
            description: BucketStatus defines the observed state of Bucket.
            type: object
        required:
        - spec
        type: object
    served: true
