apiVersion: analytics.idp.upbound.io/v1alpha1
kind: Databricks
metadata:
  name: example
spec: 
  parameters:
    region: "us-west-1"
    networkRef:
      apiVersion: networking.idp.upbound.io
      grants:
        - Observe
      kind: Network
      name: db-network
