apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xservicecontrolplanes.bootstrap.idp.upbound.io
spec:
  compositeTypeRef:
    apiVersion: bootstrap.idp.upbound.io/v1alpha1
    kind: XServiceControlPlane
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-fabriccompose-svcctp
    step: compose-svcctp
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
