apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: platformportals.bootstrap.idp.upbound.io
spec:
  compositeTypeRef:
    apiVersion: bootstrap.idp.upbound.io/v1alpha1
    kind: PlatformPortal
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-fabriccompose-portal
    step: compose-portal
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
