apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: clusters.compute.idp.upbound.io
  annotations:
    references.upbound.io/schema: '{"apiVersion":"references.upbound.io/v1alpha1","kind":"ReferenceSchema","references":[{"jsonPath":".spec.parameters.networkRef","kinds":[{"apiVersion":"networking.idp.upbound.io","kind":"NetworkClaim"}]}, {"jsonPath":".spec.parameters.serviceAccountRef","kinds":[{"apiVersion":"iam.idp.upbound.io","kind":"ServiceAccountClaim"}]}]}'
spec:
  metadata:
    annotations:
      references.upbound.io/schema: '{"apiVersion":"references.upbound.io/v1alpha1","kind":"ReferenceSchema","references":[{"jsonPath":".spec.parameters.networkRef","kinds":[{"apiVersion":"networking.idp.upbound.io","kind":"NetworkClaim"}]}, {"jsonPath":".spec.parameters.serviceAccountRef","kinds":[{"apiVersion":"iam.idp.upbound.io","kind":"ServiceAccountClaim"}]}]}'
  group: compute.idp.upbound.io
  names:
    categories:
    - crossplane
    kind: Cluster
    plural: clusters
  claimNames:
    kind: ClusterClaim
    plural: clusterclaims
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: Cluster is the Schema for the Cluster API.
        properties:
          spec:
            description: ClusterSpec defines the desired state of Cluster.
            properties:
              parameters:
                properties:
                  networkRef:
                    properties:
                      apiVersion:
                        type: string
                      grants:
                        items:
                          type: string
                        type: array
                      kind:
                        type: string
                      name:
                        type: string
                    type: object
                  serviceAccountRef:
                    properties:
                      apiVersion:
                        type: string
                      grants:
                        items:
                          type: string
                        type: array
                      kind:
                        type: string
                      name:
                        type: string
                    type: object
                  nodes:
                    type: number
                  sku:
                    type: string
                type: object
            type: object
          status:
            description: ClusterStatus defines the observed state of Cluster.
            type: object
        required:
        - spec
        type: object
    served: true
