apiVersion: compute.idp.upbound.io/v1alpha1
kind: Application
metadata:
  name: example
spec:
  parameters:
    application:
      name: guestbook-ui
      image: gcr.io/heptio-images/ks-guestbook-demo:0.2
      clusterRef:
        apiVersion: compute.idp.upbound.io/v1alpha1
        grants:
        - "*"
        kind: ClusterClaim
        name: example
        namespace: default
    # resources:
    #- name: images
    #  type: s3
    #  s3:
    #    bucketName: my-images-bucket
    #- name: database
    #  type: postgres
    #  postgres: {}
