apiVersion: compute.idp.upbound.io/v1alpha1
kind: ApplicationClaim
metadata:
  name: example
spec:
  parameters:
    application:
      name: guestbook-ui
      image: gcr.io/heptio-images/ks-guestbook-demo:0.2
      clusterRef:
        apiVersion: compute.idp.upbound.io/v1alpha1
        grants:
        - "Observe"
        kind: ClusterClaim
        name: example
        namespace: default
